-- CreateTable
CREATE TABLE "VENTAS_POR_VISITA" (
    "ID_Visita" SERIAL NOT NULL,
    "ID_Grupo" INTEGER,
    "ID_Maquina" INTEGER NOT NULL,
    "ID_Cliente" INTEGER,
    "ID_Operador" INTEGER NOT NULL,
    "Fecha_Visita" TIMESTAMP(3) NOT NULL,
    "NR_Anterior" BIGINT NOT NULL DEFAULT 0,
    "NR_Actual" BIGINT NOT NULL DEFAULT 0,
    "Total_Vendido" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "Total_Despachado" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "Unidades_Sugeridas" INTEGER NOT NULL DEFAULT 0,
    "Detalle" JSONB,
    "Firma_Fecha" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Firma_Usuario" INTEGER,
    "Firma_Origen" VARCHAR(20) NOT NULL DEFAULT 'REGISTRO',

    CONSTRAINT "VENTAS_POR_VISITA_pkey" PRIMARY KEY ("ID_Visita")
);

-- CreateIndex
CREATE UNIQUE INDEX "VENTAS_POR_VISITA_ID_Grupo_key" ON "VENTAS_POR_VISITA"("ID_Grupo");

-- CreateIndex
CREATE INDEX "VENTAS_POR_VISITA_ID_Maquina_Fecha_Visita_idx" ON "VENTAS_POR_VISITA"("ID_Maquina", "Fecha_Visita");

-- CreateIndex
CREATE INDEX "VENTAS_POR_VISITA_ID_Cliente_idx" ON "VENTAS_POR_VISITA"("ID_Cliente");

-- AddForeignKey
ALTER TABLE "VENTAS_POR_VISITA" ADD CONSTRAINT "VENTAS_POR_VISITA_ID_Maquina_fkey" FOREIGN KEY ("ID_Maquina") REFERENCES "MAQUINAS_Y_TIENDAS"("ID_Maquina") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VENTAS_POR_VISITA" ADD CONSTRAINT "VENTAS_POR_VISITA_ID_Cliente_fkey" FOREIGN KEY ("ID_Cliente") REFERENCES "CLIENTES"("ID_Cliente") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VENTAS_POR_VISITA" ADD CONSTRAINT "VENTAS_POR_VISITA_ID_Operador_fkey" FOREIGN KEY ("ID_Operador") REFERENCES "OPERADORES"("ID_Operador") ON DELETE RESTRICT ON UPDATE CASCADE;